nyohoki_meibo =
{
    {"A'Karonys"},
    {"Abide"},
    {"Able"},
    {"Abrastal"},
    {"Absi"},
    {"Agayla"},
    {"Ahlrada Ahn"},
    {"Aimless"},
    {"Aloft"},
    {"Amby Bole"},
    {"Amiss"},
    {"Anaster"},
    {"Andarist"},
    {"Anomander Rake"},
    {"Anji"},
    {"Antsy"},
    {"Aparal Forge"},
    {"Apsal'ara"},
    {"Apsalar"},
    {"Apt"},
    {"Arahathan"},
    {"Aramala"},
    {"Aranict"},
    {"Arard"},
    {"Aralt Arpat"},
    {"Aranatha"},
    {"Asane"},
    {"Ash"},
    {"Astabb"},
    {"Ay Estos"},
    {"Azra Jael"},
    {"Ba'ienrok"},
    {"Baaljagg"},
    {"Badalle"},
    {"Badan Gruk"},
    {"Badar"},
    {"Bainisk"},
    {"Bairoth Gild"},
    {"Bakal"},
    {"Balantis"},
    {"Baldick"},
    {"Balgrid"},
    {"Balm"},
    {"Banaschar"},
    {"Barack"},
    {"Baran"},
    {"Barathol Makhar"},
    {"Baria Setral"},
    {"Baruk"},
    {"Bauchelain"},
    {"Baudin"},
    {"Bavedict"},
    {"Beak"},
    {"Bedek"},
    {"Bek Okhan"},
    {"Belie"},
    {"Bell"},
    {"Bellam Nom"},
    {"Bellig Harn"},
    {"Bellurdan Skullcrusher"},
    {"Ben Adaephon Delat"},
    {"Bendal Home"},
    {"Beneth"},
    {"Bent"},
    {"Beroke Soft Voice"},
    {"Beru"},
    {"Bidithal"},
    {"Binadas Sengar"},
    {"Biri"},
    {"Bivatt"},
    {"Blend"},
    {"Blind"},
    {"Blistig"},
    {"Bluepearl"},
    {"Blues"},
    {"Borduke"},
    {"Bottle"},
    {"Bowl"},
    {"Borrug"},
    {"Braven Tooth"},
    {"Brayderal"},
    {"Bre'neigan"},
    {"Breath"},
    {"Brethless"},
    {"Brevity"},
    {"Brevity"},
    {"Brohl Handar"},
    {"Brolos Haran"},
    {"Brukhalian"},
    {"Brullyg"},
    {"Bruthen Trana"},
    {"Brys Beddict"},
    {"Bubryd"},
    {"Bucklund"},
    {"Bugg"},
    {"Buke"},
    {"Bula"},
    {"Bult"},
    {"Burnt"},
    {"Burnt Rope"},
    {"Buruk the Pale"},
    {"Cafal"},
    {"Caladan Brood"},
    {"Calm"},
    {"Calot"},
    {"Cannig Tol"},
    {"Cartographer"},
    {"Chalas"},
    {"Challice D'Arle"},
    {"Chase"},
    {"Chaur"},
    {"Chenned"},
    {"Chert"},
    {"Chillbais"},
    {"Choram Irard"},
    {"Circle Breaker"},
    {"Clasp"},
    {"Clip"},
    {"Coll"},
    {"Coltaine"},
    {"Coop"},
    {"Corabb Bhilan Thenu'alas"},
    {"Cord"},
    {"Corinn"},
    {"Corlo"},
    {"Cotillion"},
    {"Cowl"},
    {"The Crippled God"},
    {"Crokus Younghand"},
    {"Crone"},
    {"Crump"},
    {"Curdle"},
    {"Cuttle"},
    {"Cynnigig"},
    {"D'rek"},
    {"Damisk"},
    {"Darist"},
    {"Dassem Ultor"},
    {"Dathenar Fandoris"},
    {"Dayliss"},
    {"Deadsmell"},
    {"Dejim Nebrahl"},
    {"Delist"},
    {"Delum Thord"},
    {"Derudan"},
    {"Desra"},
    {"Dessembrae"},
    {"Detoran"},
    {"Diligence"},
    {"Ditch"},
    {"Doan"},
    {"Draconus"},
    {"Drawfirst"},
    {"Duiker"},
    {"Dujek Onearm"},
    {"Dunsparrow"},
    {"Duryl"},
    {"Ebron"},
    {"Edgewalker"},
    {"Eldat Pressan"},
    {"Emancipor Reese"},
    {"Endest Silann"},
    {"Enedictal"},
    {"Enias"},
    {"Equity"},
    {"Erekala"},
    {"The Errant"},
    {"Estraysian D'Arle"},
    {"Ethume"},
    {"Exigent"},
    {"Ezgara Diskanar"},
    {"Faint"},
    {"Faradan Sort"},
    {"Farakalian"},
    {"Faro Balkat"},
    {"Fast"},
    {"Fayelle"},
    {"Fear Sengar"},
    {"Febryl"},
    {"Felash"},
    {"Felisin Paran"},
    {"Felisin Younger"},
    {"Feather Witch"},
    {"Ferrule"},
    {"Festian"},
    {"Fiddler"},
    {"Fingers"},
    {"Fisher"},
    {"Fisherman"},
    {"Flashwit"},
    {"Freedom"},
    {"Futhgar"},
    {"Gaelar Throe"},
    {"Gall"},
    {"Galt"},
    {"Gamet"},
    {"Ganath"},
    {"Ganoes Stabro Paran"},
    {"Ganrod"},
    {"Garath"},
    {"Gaunt-Eye"},
    {"Gaz"},
    {"Gear"},
    {"Gerun Eberict"},
    {"Gesler"},
    {"Gethol"},
    {"Glanno Tarp"},
    {"Glisten"},
    {"Gorlas Vidikas"},
    {"Gothos"},
    {"Gradithan"},
    {"Grave"},
    {"Green Pig"},
    {"Greyfrog"},
    {"Grub"},
    {"Gruntle"},
    {"Gryllen"},
    {"Gu'Rull"},
    {"Gullstream"},
    {"Gumble"},
    {"Gunth Mach"},
    {"Gunth'an Acyl"},
    {"Hadralt"},
    {"Haggraf"},
    {"Hairlock"},
    {"Thalad the Giant"},
    {"Halfpeck"},
    {"Handmaiden"},
    {"Hanut Orr"},
    {"Hanavat"},
    {"Hannan Mosag"},
    {"Hanno"},
    {"Hanradi Khalag"},
    {"Haradas"},
    {"Hareb"},
    {"Harlest"},
    {"Harllo"},
    {"Harllo (Younger)"},
    {"Hattar"},
    {"Hayrith"},
    {"Heboric Light Touch"},
    {"Hedge"},
    {"Hejun"},
    {"Held"},
    {"Hellian"},
    {"Henar Vygulg"},
    {"Henarist"},
    {"Hentos Ilm"},
    {"Hestand"},
    {"Hetan"},
    {"Honey"},
    {"Hood"},
    {"Horult"},
    {"Hostille Rator"},
    {"Hulad"},
    {"Huldo"},
    {"Hulbat"},
    {"Hull Beddict"},
    {"Humble Measure"},
    {"Humbrall Taur"},
    {"Hunt"},
    {"Hurlochel"},
    {"Ibb"},
    {"Ibra Gholan"},
    {"Icarium"},
    {"Ilm Absinos"},
    {"Imrahl"},
    {"Imroth"},
    {"Inal"},
    {"Inchers"},
    {"Inistal Ovan"},
    {"Iparth Erule"},
    {"Ipshank"},
    {"Irilta"},
    {"Iron Bars"},
    {"Irp"},
    {"Iskaral Pust"},
    {"Itkovian"},
    {"Janall"},
    {"Janath Anar"},
    {"Jarabb"},
    {"Jastara"},
    {"Jerlarkan"},
    {"Jhedel"},
    {"Jhenna"},
    {"Jhess"},
    {"Jibb"},
    {"Job Bole"},
    {"Jorrick Sharplance"},
    {"Jorrude"},
    {"Jula Bole"},
    {"K'azz D'Avore"},
    {"K'rul"},
    {"Kadagar Fant"},
    {"Kadaspala"},
    {"Kalb the Silent Hunter"},
    {"Kahlt"},
    {"Kalam Mekhar"},
    {"Kallor"},
    {"Kalt Urmanal"},
    {"Kalyth"},
    {"Kamist Reloe"},
    {"Karnadas"},
    {"Karos Invictad"},
    {"Karpolan Demesand"},
    {"Karsa Orlong"},
    {"Kasanal"},
    {"Kedeviss"},
    {"Keneb"},
    {"Kerul"},
    {"Kesen"},
    {"Kessgan"},
    {"Kettle"},
    {"Kholb Harat"},
    {"Kig Aven"},
    {"Kilava"},
    {"Kilmandaros"},
    {"Kimloc"},
    {"Kindly"},
    {"Kiska"},
    {"Kisswhere"},
    {"Knuckles"},
    {"Kor Thuran"},
    {"Korbal Broach"},
    {"Korbolo Dom"},
    {"Korlat"},
    {"Koryk"},
    {"Kron"},
    {"Krughava"},
    {"Kruppe"},
    {"Krute of Talient"},
    {"Kulat"},
    {"Kulp"},
    {"Kulpath"},
    {"Kuru Qan"},
    {"L'oric"},
    {"Lady Envy"},
    {"Laerdas"},
    {"Lanas Tog"},
    {"Lap Twirl"},
    {"Laseen"},
    {"Last"},
    {"Lazan Door"},
    {"Leff"},
    {"Legana Breed"},
    {"Lenestro"},
    {"Leoman of the Flails"},
    {"Lera Epar"},
    {"Letur Anict"},
    {"Lim"},
    {"Limp"},
    {"List"},
    {"Lobe"},
    {"Lock"},
    {"Logros"},
    {"Lookback"},
    {"Lorn"},
    {"Lostara Yil"},
    {"Lubben"},
    {"Lull"},
    {"Lutes"},
    {"Madan'tul Rada"},
    {"Madrun"},
    {"Malachar"},
    {"Mallet"},
    {"Mallick Rel"},
    {"Mammot"},
    {"Mape"},
    {"Mappo Runt"},
    {"Maral Eb"},
    {"Marble"},
    {"Masan Gilani"},
    {"Masarch"},
    {"Master Quell"},
    {"Mathok"},
    {"Matra Brith"},
    {"Maybe"},
    {"Mayen"},
    {"Mayfly"},
    {"Mebra"},
    {"Meese"},
    {"Melest"},
    {"Menandore (Sister Dawn)"},
    {"Mesker Setral"},
    {"Messremb"},
    {"The Mhybe"},
    {"Midik Buhn"},
    {"Minala"},
    {"Mincer"},
    {"Moak"},
    {"Moby"},
    {"Mogora"},
    {"Mok"},
    {"Monkrat"},
    {"Monok Ochem"},
    {"Moroch Nevath"},
    {"Mosel"},
    {"Mowri"},
    {"Mudslinger"},
    {"Mulch"},
    {"Mulvan Dreader"},
    {"Munug"},
    {"Murillio"},
    {"Myrla"},
    {"Nappet"},
    {"Natarkas"},
    {"Nekal Bara"},
    {"Neller"},
    {"Nenanda"},
    {"Nep Furrow"},
    {"Netok"},
    {"Nether"},
    {"Nethpara"},
    {"Nifadas"},
    {"Nightchill"},
    {"Nil"},
    {"Nilbanas"},
    {"Nimander Golit"},
    {"Nisall"},
    {"Nkalian"},
    {"Nok"},
    {"Nom Kala"},
    {"Norul"},
    {"Nose Stream"},
    {"Noto Boil"},
    {"Nulliss"},
    {"Obo"},
    {"Ocelot"},
    {"Okral Lom"},
    {"Olar Ethil"},
    {"Old Hunch Arbat"},
    {"Oleg Vikat"},
    {"Onos T'oolan"},
    {"Onrack"},
    {"Onyx"},
    {"Orbyn 'Truthfinder'"},
    {"Orenas"},
    {"Orfantal"},
    {"Ormly"},
    {"Ormulogun"},
    {"Paderunt"},
    {"Pahlk"},
    {"Pallid"},
    {"Panek"},
    {"The Pannion Seer"},
    {"Parald"},
    {"Pearl"},
    {"Pella"},
    {"Phaed"},
    {"Phyrlis"},
    {"Picker"},
    {"Pinosel"},
    {"Pithy"},
    {"Placid"},
    {"Pores"},
    {"Pormqual"},
    {"Possum"},
    {"Pralt"},
    {"Pran Chole"},
    {"Pravalak Rim"},
    {"Prazek Goul"},
    {"Precious Thimble"},
    {"Primly"},
    {"Prist"},
    {"Prophet Seech"},
    {"Pule"},
    {"Pully"},
    {"Pullyk Alar"},
    {"Quillas Diskanar"},
    {"Raband"},
    {"Raest"},
    {"Ralata"},
    {"Rallick Nom"},
    {"Ramp"},
    {"Ranal"},
    {"Rath'Beru"},
    {"Rath'Burn"},
    {"Rath'Dessembrae"},
    {"Rath'D'rek"},
    {"Rath'Fanderay"},
    {"Rath'Fener"},
    {"Rath'Hood"},
    {"Rath'Oponn"},
    {"Rath'Queen of Dreams"},
    {"Rath'Shadowthrone"},
    {"Rath'Togg"},
    {"Rath'Trake"},
    {"Rautos Hivanar"},
    {"Reccanto Ilk"},
    {"Redmask"},
    {"Reem"},
    {"Reliko"},
    {"Rellock"},
    {"Rethal"},
    {"Reverence"},
    {"Rhulad Sengar"},
    {"Rib"},
    {"Rind"},
    {"Rissarh"},
    {"Roach"},
    {"Rood"},
    {"Ruby"},
    {"Rucket"},
    {"Rudd"},
    {"Rud Ellale"},
    {"Ruffle"},
    {"Rumjugs"},
    {"Runter"},
    {"Run'Thurvian"},
    {"Ruthan Gudd"},
    {"Rutt"},
    {"Ryllandaras"},
    {"Rystalle Ev"},
    {"Rythe Bude"},
    {"Rythok"},
    {"Sad"},
    {"Saddic"},
    {"Sag'Churok"},
    {"Salind"},
    {"Salk Elan"},
    {"Saltlick"},
    {"Samar Dev"},
    {"Sandalath Drukorlat"},
    {"Sands"},
    {"Sathboro Rangar"},
    {"Sawark"},
    {"Scabandari Bloodeye"},
    {"Scant"},
    {"Scillara"},
    {"Scint"},
    {"Scorch"},
    {"Scrawl"},
    {"Scurve"},
    {"Seal"},
    {"Seba Krafar"},
    {"Seerdomin"},
    {"Selush"},
    {"Selv"},
    {"Senu"},
    {"Seren Pedac"},
    {"Serenity"},
    {"Serrat"},
    {"Setoc"},
    {"Sha'ik"},
    {"Shadowthrone"},
    {"Shan"},
    {"Shand"},
    {"Shank"},
    {"Shard"},
    {"Shardan Lim"},
    {"Sharl"},
    {"Sheb"},
    {"Shedunul"},
    {"Shelemasa"},
    {"Sheltatha Lore (Daughter Dusk)"},
    {"Shoaly"},
    {"Shortnose"},
    {"Shurq Elalle"},
    {"Sidlis"},
    {"Silanah"},
    {"Silchas Ruin"},
    {"Silgar"},
    {"Silverfox"},
    {"Simtal"},
    {"Sinn"},
    {"Sinter"},
    {"Sirryn Kanar"},
    {"Sister Spite"},
    {"Skanarow"},
    {"Skim"},
    {"Skintick"},
    {"Skorken Kaban"},
    {"Skulldeath"},
    {"Skwish"},
    {"Smiles"},
    {"Snell"},
    {"Sobelone"},
    {"Sordiko Qualm"},
    {"Sormo E'nath"},
    {"Sorry"},
    {"Spax"},
    {"Spindle"},
    {"Spinnock Durav"},
    {"Squint"},
    {"Stacker"},
    {"Stavi"},
    {"Stillis"},
    {"Stolmen"},
    {"Stonny Menackis"},
    {"Storii"},
    {"Stormy"},
    {"Stahl"},
    {"Strap Mull"},
    {"Straw"},
    {"Strong Rall"},
    {"Studlock"},
    {"Stump"},
    {"Sty"},
    {"Sukul Ankhadu (Sister Dapple)"},
    {"Sulkit"},
    {"Sulmar"},
    {"Sulty"},
    {"Sunrise"},
    {"Surgen Ress"},
    {"Sweetcreek"},
    {"Sweetlard"},
    {"Sweetest Sufferance"},
    {"Synyg"},
    {"T'Amber"},
    {"T'morol"},
    {"Talo Krafar"},
    {"Talamandas"},
    {"Tanal Yathvanar"},
    {"Tanakalian"},
    {"Taralack Veed"},
    {"Tarr"},
    {"Tattersail"},
    {"Tavore Paran"},
    {"Tavos Pond"},
    {"Tayschrenn"},
    {"Taxilian"},
    {"Tehol Beddict"},
    {"Telorast"},
    {"Temul"},
    {"Temper"},
    {"Tene Baralta"},
    {"Thenik the Shattered"},
    {"Theradas Buhn"},
    {"Tholis"},
    {"Thom Tissy"},
    {"Thordy"},
    {"Throatslitter"},
    {"Thurule"},
    {"Til'Aras Benok"},
    {"Tiserra"},
    {"Toc the Elder"},
    {"Toc the Younger"},
    {"Toes"},
    {"Tomad Sengar"},
    {"Topper"},
    {"Torahval Delat"},
    {"Torun"},
    {"Torrent"},
    {"Torvald Nom"},
    {"Touchy"},
    {"Travale"},
    {"Treach"},
    {"Trenech"},
    {"Triban Gnol"},
    {"Trissin"},
    {"Trotts"},
    {"Trull Sengar"},
    {"Truth"},
    {"Tulip"},
    {"Tugg"},
    {"Tulas Shorn"},
    {"Tumlit"},
    {"Turban Orr"},
    {"Turble"},
    {"Twist"},
    {"Ublala Pung"},
    {"Udinaas"},
    {"Ulag Togtil"},
    {"Ultentha"},
    {"Ulshun Pral"},
    {"Unn"},
    {"Unnutal Hebaz"},
    {"Untilly Rum"},
    {"Urb"},
    {"Ursto Hoobutt"},
    {"Uru Hela"},
    {"Urugal the Woven"},
    {"Urul"},
    {"Uruth"},
    {"Vaneb"},
    {"Varat Taun"},
    {"Vastly Blank"},
    {"Vedith"},
    {"Velbara"},
    {"Venaz"},
    {"Venitt Sathad"},
    {"Vildrom"},
    {"Virrick"},
    {"Vorcan"},
    {"Whiskeyjack"},
    {"Widdershins"},
    {"Wimble Thrup"},
    {"Withal"},
    {"Wither"},
    {"Yan Tovis"},
    {"Yedan Derryg"},
}